# Generated by Django 4.2.4 on 2023-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='user',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
