# Generated by Django 4.2.4 on 2023-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentuser_user_studentuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
