# Generated by Django 4.2.4 on 2023-08-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(choices=[('MATHS', 'Maths'), ('FURTHER MATHS', 'Further Maths')], max_length=30, null=True)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('mark_scheme', models.CharField(max_length=100, null=True)),
                ('answer_box', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
