# Generated by Django 4.2.4 on 2023-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_question_image_alter_question_mark_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
