# Generated by Django 4.2.4 on 2023-09-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadratics', models.IntegerField(blank=True, null=True)),
                ('equations_and_inequalities', models.IntegerField(blank=True, null=True)),
                ('graphs_and_transformations', models.IntegerField(blank=True, null=True)),
                ('straight_line_graphs', models.IntegerField(blank=True, null=True)),
                ('circles', models.IntegerField(blank=True, null=True)),
                ('trigonometry', models.IntegerField(blank=True, null=True)),
                ('differentiation', models.IntegerField(blank=True, null=True)),
                ('integration', models.IntegerField(blank=True, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='FurtherMathsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differentiation', models.IntegerField(blank=True, null=True)),
                ('integration', models.IntegerField(blank=True, null=True)),
                ('methods_in_calculus', models.IntegerField(blank=True, null=True)),
                ('matrices', models.IntegerField(blank=True, null=True)),
                ('polar_coordinates', models.IntegerField(blank=True, null=True)),
                ('hyperbolic_functions', models.IntegerField(blank=True, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentuser')),
            ],
        ),
    ]
